// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6UGWcO5SGztjxbELWIMp88Du6eRhsuxg',
    appId: '1:439126726416:web:22b7854512d57801bb3795',
    messagingSenderId: '439126726416',
    projectId: 'social-media01-8a2ec',
    authDomain: 'social-media01-8a2ec.firebaseapp.com',
    storageBucket: 'social-media01-8a2ec.firebasestorage.app',
    measurementId: 'G-HVEM6K647P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDRurvJ-qwPJNHXkb-rca9FtQKPdTNZGk',
    appId: '1:439126726416:android:c03c12e1289581f2bb3795',
    messagingSenderId: '439126726416',
    projectId: 'social-media01-8a2ec',
    storageBucket: 'social-media01-8a2ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzqd2ODkS2Y5iUJWdN5ZaUBPJ7Sl_UERo',
    appId: '1:439126726416:ios:d17ea376eb7c225bbb3795',
    messagingSenderId: '439126726416',
    projectId: 'social-media01-8a2ec',
    storageBucket: 'social-media01-8a2ec.firebasestorage.app',
    androidClientId: '439126726416-7esntqffdubt8j49u6vkt1e5nlcurvku.apps.googleusercontent.com',
    iosClientId: '439126726416-uv545ajbeq20m3h9cur4t7f0s6if1btt.apps.googleusercontent.com',
    iosBundleId: 'com.example.isdApp',
  );
}
